### ISSUE TITLE
Log tracker

### ISSUE THREAD

**Issue by jooyoungseo** [xability/maidr-legacy#66]
As we discussed today, please implement an event-driven log tracker.

- [x] Log tracker needs to get started as a page is loaded.

- [x] We may want to bind log tracker to each SVG object.

- [x] Default log file format: JSON

- [x] Use `F10` to bring up "Save As" dialog box for exporting log file.

- [x] Use sessions and cookies to address multi user access.

- [x] In our user studies, we will embed each plot in separate pages, which means we may need to append multiple log data from the same user agent until they explicitly press `F10`.

- [x] Structure (please feel free to add more if any):

1. graph type

1. timestamp

1. keystroke

1. current modes (BTS)

1. misc settings (like custom frequency range, volume, braille display size, etc)

1. current position on chart

1. user OS platform info

1. user browser and version

**Comment by ellvix** [comment]
Everything tracked, awaiting feedback. 

Still need cookies and session data for multi page use. Are we going to be getting any users in the EU? Would need a cookie policy accept interface.

**Comment by jooyoungseo** [comment]
@ellvix -- Fantastic! Looks great to me!! Thanks for implementing this. I am sharing my testing results below (I also have pasted my log at the bottom of this comment).

- [ ] `userAgent` property does not seem to match with what I actually use. I have tested the log tracker in Chrome Version 108.0.5359.125 (Official Build) (64-bit) on Windows. However, it records it as `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"`.

- [ ] `platform` property does not match with my OS platform. As mentioned above, I tested the log tracker on Windows 64 bit (the Chrome version is also x64). However, currently, it is recorded as `"Win32"`.

- [ ] `brailleMode` property is not being recorded so that its toggle status is currently missing.

- [ ] `scatterplotLayer` property is only applicable for scatterplot type, and needs to be taken out for other types. As a better idea, we may implement a general layer concept and property for all types of graphs.

- [ ] `textMode` property value is a string data type when it is either `terse` or `verbose`. I assume that it would get a numeric data type (i.e., 0) when it is set to off. On the other hand, `sonificationMode` property value always gets a numeric data type (0 or 1). We may want to keep string data type across all the btsMode like "on", "off", "verbose", "terse", etc.

- [ ] `focus` property can be used for greater detailed info if possible (i.e., group.position). In boxplot, for example, it can be "subcompact.High", "suv.75%", etc. In barplot, it could be "Premium", "VeryGood", etc (since no group info is available in our bar plot sample, the group prefix can be omitted.) For heatmap, it could be `{xGroup.yGroup}`; for scatterplot, it could be `{xPosition}`.

``` json
{
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "language": "en-US",
    "platform": "Win32",
    "events": [
        {
            "timestamp": 2406.399999999994,
            "time": "Wed Jan 04 2023 08:22:53 GMT-0600 (Central Standard Time)",
            "key": "Shift",
            "which": 16,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": true,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 2455.399999999994,
            "time": "Wed Jan 04 2023 08:22:53 GMT-0600 (Central Standard Time)",
            "key": "Tab",
            "which": 9,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": true,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 3496.499999999971,
            "time": "Wed Jan 04 2023 08:22:54 GMT-0600 (Central Standard Time)",
            "key": "ArrowRight",
            "which": 39,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 3929.8000000000175,
            "time": "Wed Jan 04 2023 08:22:54 GMT-0600 (Central Standard Time)",
            "key": "ArrowRight",
            "which": 39,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 4218.8000000000175,
            "time": "Wed Jan 04 2023 08:22:54 GMT-0600 (Central Standard Time)",
            "key": "ArrowRight",
            "which": 39,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 4497.399999999994,
            "time": "Wed Jan 04 2023 08:22:55 GMT-0600 (Central Standard Time)",
            "key": "ArrowRight",
            "which": 39,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 5049.1999999999825,
            "time": "Wed Jan 04 2023 08:22:55 GMT-0600 (Central Standard Time)",
            "key": "Control",
            "which": 17,
            "altKey": false,
            "ctrlKey": true,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 5124.399999999994,
            "time": "Wed Jan 04 2023 08:22:55 GMT-0600 (Central Standard Time)",
            "key": "ArrowRight",
            "which": 39,
            "altKey": false,
            "ctrlKey": true,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 5757.3000000000175,
            "time": "Wed Jan 04 2023 08:22:56 GMT-0600 (Central Standard Time)",
            "key": "Control",
            "which": 17,
            "altKey": false,
            "ctrlKey": true,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 5856.499999999971,
            "time": "Wed Jan 04 2023 08:22:56 GMT-0600 (Central Standard Time)",
            "key": "ArrowLeft",
            "which": 37,
            "altKey": false,
            "ctrlKey": true,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 7286.600000000006,
            "time": "Wed Jan 04 2023 08:22:58 GMT-0600 (Central Standard Time)",
            "key": "ArrowDown",
            "which": 40,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 8301.399999999994,
            "time": "Wed Jan 04 2023 08:22:59 GMT-0600 (Central Standard Time)",
            "key": "ArrowDown",
            "which": 40,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 9189.49999999997,
            "time": "Wed Jan 04 2023 08:22:59 GMT-0600 (Central Standard Time)",
            "key": "ArrowUp",
            "which": 38,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 9675.800000000017,
            "time": "Wed Jan 04 2023 08:23:00 GMT-0600 (Central Standard Time)",
            "key": "ArrowUp",
            "which": 38,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        },
        {
            "timestamp": 9947.699999999983,
            "time": "Wed Jan 04 2023 08:23:00 GMT-0600 (Central Standard Time)",
            "key": "ArrowUp",
            "which": 38,
            "altKey": false,
            "ctrlKey": false,
            "shiftKey": false,
            "focus": "svg",
            "minX": 0,
            "maxX": 639.05,
            "minY": 0,
            "chartType": "boxplot",
            "MAX_FREQUENCY": 1000,
            "MIN_FREQUENCY": 200,
            "NULL_FREQUENCY": 100,
            "MAX_SPEED": 2000,
            "MIN_SPEED": 50,
            "INTERVAL": 50,
            "volume": 0.4,
            "autoPlayRate": 250,
            "color": "#03C809",
            "brailleDisplayLength": 18,
            "toneDuration": 0.2,
            "autoPlayOutlierRate": 30,
            "autoPlayPointsRate": 30,
            "textMode": "terse",
            "sonificationMode": 1,
            "scatterplotLayer": 0
        }
    ]
}
```

**Comment by jooyoungseo** [comment]
@ellvix 

> Are we going to be getting any users in the EU?

At this point, that's not planned. Probably, we can scale up our system later (not yet in the current stage).

**Comment by jooyoungseo** [comment]
@yilinxia -- Please feel free to share your feedback with us.

**Comment by yilinxia** [comment]
SUre. I have a few questions which might need futher clarification

**modalities**
1.  It is obvious to find whether the `textMode`and `sonificationMode` have been turned on, but right now it is hard to tell whether the brailleMode is turn on or not
2. If the event is time-point based, does the time difference of two events e.g., E1 and E2 means E1 have lasted? Besides the sequence of modalities, the time percentage might be something we are also interested in

**keys**
1. What are the possible values for `key` attribute? Looks like it has the special key or arrow key value, while the control key can also be inferred from `altKey`, `ctrlKey`, `shiftKey`
2. Do we need to track the "space" key as well?

**other_variables**
1.  What does `which:36` mean?
2. Regarding the `focus`, probably we can use the result of text mode? OR we can also summarize it when coding participants' interview

**Comment by ellvix** [comment]
@jooyoungseo 

Differences in application and OS are in name only, but should be accurate. You can take a look yourself and see what you want to use. Open Inspector and type `navigator` in console to see a list of everything we have available. `oscpu` might be better? `oscpu: "Windows NT 10.0; Win64; x64"` Same for Chrome version. `userAgent` has the most info, but there are other fields. 

I'll take a look at focus more. Currently it gives literal keyboard focus (which is useful in other ways). We give `position` but will need to extrapolate to give chart specific data (including labels etc). That's probably more useful to you and easier to read so we'll do that. 

EU users: If we're  not doing that then we can implement cookies / session data very quickly.

**Comment by ellvix** [comment]
@yilinxia 

Modalities:

1. Braille mode is not in because I'm stupid and deleted it by accident while bugfixing. I'll add it in shortly lol.
2. Correct, it's time point based, so difference is the duration. Can you explain more about time percentage?

Keys:

1. `key` is human readable-ish and probably most useful. Not sure what all values are but we can investigate.
2. We track everything. Space will be recorded but since it's not a 'real' change maybe it can be handled differently?

Other:

1. `which` is the keyCode of the key pressed. Like, Space = 32, Enter = 13, etc. Useful as a backup in case `key` fails us. 
2. Agreed. Focus should behave differently and we'll address that.

**Comment by yilinxia** [comment]
@ellvix Thank you for the explaination !
For the time percentage, we can also analyze the time durations participants used for a certain modalities across the study or for a particular visualization to see if using certain modality take more time than the others because 1) the modality unveil more information OR 2) difficult to intepret

**Comment by ellvix** [comment]
I could add x and y label data for boxplot, but need help on standardizing. Do we need this data for all charts? It doesn't exist for all charts but we could add what data exist? Like, for barplot just do x label. 

Better yet, why don't we just log what text is being displayed in text? That gives you everything, including data. Like, what if the user is playing around between 2 points and you're like "what the hell is going on here, are the controls broken? what are they doing?" but then you look at the actual data and say "oh yeah ok those 2 points are messed up I'd be doing that too".

**Comment by ellvix** [comment]
Update, let's use x and y label, essentially simulating verbose mode for both vertical and horizontal movement. 

Try adding to Display, and creating a separate output just for the log. Display is useful since all the data is already there.

**Comment by ellvix** [comment]
For refresh / clearing, we're going to let Ctrl-F5 do the work, so use either session data, or otherwise clear cookies manually.
